# This is a basic workflow to help you get started with Actions

name: TO Duplicate name


# Controls when the workflow will run
on:
  push:
    branches:
      - main

  workflow_dispatch:
  # Define the inputs of this Workflow
    inputs:
      motorTests-PM216:
        description: 'Run for PM216'
        type: boolean
        required: false
      motorTests-PM291:
        description: 'Run for PM291'
        type: boolean
        required: false
      motorTests-PM292:
        description: 'Run for PM292'
        type: boolean
        required: false
      motorTests-PM293:
        description: 'Run for PM293'
        required: false
        type: boolean
      clusterTest-TableSignature:
        description: 'Run Cluster Test'
        required: false
        type: boolean  
      
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: [self-hosted, mypc]
    steps:       
        - name: Copy output with Powershell core
          id: output_res_pwsh
          run: echo "TEST"          
