# This is a basic workflow to help you get started with Actions

name: DuplicateWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: First 
        run: echo build 
  
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build 
    strategy:
      matrix:
        tests: ["TEST"]
      max-parallel: 1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run Shell Script
        if: ${{ ! github.event.pull_request.draft }}
        run: | 
          echo first_way_of_if_statement
          echo ${{matrix.tests}}
          echo ${{github.event}}
          sleep 10s
      
      - name: Run Shell Script V2
        if: github.event.pull_request.draft == false
        run: | 
          echo second_way_of_if_statement
          echo ${{matrix.tests}}
          echo ${{github.event}}
          sleep 10s
