name: Check Pull Request Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-tests:
    runs-on: [self-hosted, mypcrunner]
    steps:
    - name: Check if tests passed at some point
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await octokit.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload.pull_request.head.sha,
          });
          const checkRuns = response.data.check_runs;
          let testsPassed = false;
          for (const checkRun of checkRuns) {
            if (checkRun.conclusion === 'success') {
              testsPassed = true;
              break;
            }
          }
          console.log(`Tests passed at some point: ${testsPassed}`);
