# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Required-test report
  # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: First 
        run: |
          echo build 
  
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build  
    steps:
        - name: Checkout the running branch
          uses: actions/checkout@v2
        - name: Set up MATLAB
          uses: matlab-actions/setup-matlab@v1
#         - name: Run Matlab Script
#           run: matlab -softwareopengl -batch "testingPathControl()"

#         - name: Copy output to variable
#           id: output_res
#           run: |
#             echo $(matlab -softwareopengl -batch "testingPathControl()") >> $GITHUB_OUTPUT
#         - name: Echo Result
#           run: |
#             echo ${{join(steps.output_res.outputs.*,'\n')}}
#         - name: Check if statement
#           if: ${{join(steps.output_res.outputs.*,'\n')}} == "B case"
#           run: |
#             echo "it works"
        # Find changed directories  
#         - name: Get changed files
#           id: changed-files
#           uses: tj-actions/changed-files@v35
        # Find changed directories  
        
#         - name: Echo changed files
#           run : |
#             for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#               echo $file >> changed_files.txt
#             done
          
#         - name: Find which tests should be performed
#           run: matlab -softwareopengl -batch "getTestsToPerform();"    
            
            
        - name: Find the changed files
          run: |
            git fetch
            git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > changed_files.txt
            
        # Find which tests should be performed and save to output variable
        - name: Test matlab file
          run: matlab -softwareopengl -batch "getTestsToPerform()"
        

        - name: Copy output to variable
          id: output_res
          run: |
            echo $(matlab -softwareopengl -batch "getTestsToPerform()") >> $Env:GITHUB_OUTPUT
        
        # Echo results
        - name: Echo Result
          run: |
            echo ${{join(steps.output_res.outputs.*,'\n')}}

        # Check if refernce motor tests are needed
        - name: Check if statement
          if: ${{join(steps.output_res.outputs.*,'\n')}} == "AB"
          run: |
            echo "If statemnet works"
            
        - name: Check contains statement
          if: contains(${{join(steps.output_res.outputs.*,'\n')}},"A")
          run: echo "Contains works"

        - name: Copy output to variable second way
          id: output_res_v2
          run: |
            echo var=$(matlab -softwareopengl -batch "getTestsToPerform()") >> $GITHUB_OUTPUT
        - name: Echo Result v2
          run: |
            echo ${{steps.output_res_v2.outputs.var}}
